/*******************************
*                              *
* Trabalho Compiladores 2019.2 *
* Prof. Isidro                 *
********************************
* Arthur Navarro Guedes        *
* RA: 11085314                 *
*                              *
*                              *
*******************************/

#include "PixCompiler.h"
#include <conio.h>  /* kbhit() */
#define IDMAX (255 - NPALLET)

FILE * bmp;                 /* BMP source file */
uint8_t * tokenArray;       /* Token array - Stores source file's token list*/
uint32_t tokenCount = 0;    /* Total of tokens in array */
id * idArray;            /* Identifier array - Stores all identifiers in source file */
uint32_t idCount = 0;       /* Total of identifiers in array */



void createIdArray()
{
    idArray = (id *)malloc(IDMAX*sizeof(id));
}

void createTokenArray(uint32_t size)
{
    tokenArray = (uint8_t *) malloc(size);
}

uint8_t tokenCompare(Pixel p)
{
    uint8_t i;

    for(i = 0; i < NPALLET; i++)
    {
        if(p.integer == pallet.pixArray[i].integer) return i;
    }

    return i;
}

void addTokenArray(uint8_t value)
{
    tokenArray[tokenCount] = value;
    tokenCount++;
}

void addIdArray(Pixel p,Token token)
{
    if(idCount < IDMAX)
    {
        idArray[idCount].color = p;
        idArray[idCount].token = token;
        idCount++;
    }
}

uint8_t idCompare(Pixel p, uint32_t pos)
{
    uint8_t i;

    for(i = 0; i < idCount; i++)
    {
        if(p.integer == idArray[i].color.integer) return i;
    }
    printf("New id! Position: %d Token: %d\n",pos,ID + i);
    addIdArray(p,ID + i);

    return i;
}

Token getTokenFromPixelArray(uint32_t i)
{
    Token token = tokenCompare(pixelArray[i]);

    if(token == ID) token += idCompare(pixelArray[i],i);

    return token;

}

uint8_t lexicalAnalyzer(FILE * bmp, uint32_t pixelCount)
{
    Token token;

    printf("Initializing Lexical Analyzer\n");

    for(uint32_t i = 0; i < pixelCount ; i++)
    {
        token = getTokenFromPixelArray(i);

        addTokenArray(token);

        if(isNextTokenValue(token))
        {
            /*UNFINISHED CODE */
            if(token == STRING)
            {
                token = tokenCompare(pixelArray[i]);
                if(token == QUOT)
                {
                    addTokenArray(QUOT);
                    i++;

                    while(tokenCompare(pixelArray[i]) != QUOT)
                    {
                        i++;
                    }

                    addTokenArray(QUOT);
                    i++;
                }

            }
            else
            {

            }
            /* UNFINISHED CODE */
        }
    }

    return 0;
}

void increaseCounter(uint32_t *countPtr)
{
    *countPtr++;
}

Token getToken(uint32_t countPtr)
{
    return tokenArray[countPtr];
}

char * intToString(uint64_t value)
{
    char * str = (char *) malloc(22);
    sprintf(str,"%I64u",value);

    return str;
}

char * floatToString(float f)
{
    char * str = (char *) malloc(10);
    sprintf(str,"%f",f);

    return str;
}

char * pixStringToString(uint32_t * counter)
{
    char * buffer = (char *) malloc(200);
    uint32_t quotInt;
    uint8_t i;

    quotInt = pallet.pixels.quotColor.integer;


    for(i = 0; pixelArray[i].integer != quotInt; i++)
        buffer[i] = pixelArray[i].pix.b;

    *counter += i;

    return buffer;

}

char * idToText(uint8_t token) /* UNFINISHED */
{
    char * buffer = (char *) malloc(7);
    sprintf(buffer,"var%d",token - ID + 1);

    return buffer;
}

void createCCode() /* UNFINISHED */
{
    FILE * cFile = fopen("out.c","w");
    uint32_t i;
    fputs("/* Code generated by PixCompiler, by Arthur N. Guedes*/\n\n\n",cFile);

    Token token;
    printf("Creating C code file.\n");
    for(i = 0, token = getTokenFromPixelArray(i); token != ENDOFCODE;  token = getTokenFromPixelArray(++i))
    {
        printf("%s ", tokenName[token]);
        if(isNextTokenValue(token))
        {
            switch (token)
            {
            case INT:
                fputs(intToString(pixelArray[++i].integer),cFile);
                break;
            case LONG:
                fputs(intToString(pixelArray[++i].integer<<24 | pixelArray[++i].integer), cFile);
                break;
            case FLOAT:
                fputs(floatToString(pixelToFloat(pixelArray[++i])), cFile);
                break;
            case STRING:
                fputc('"',cFile);
                i++;
                fputs(pixStringToString(&i),cFile);
                fputc('"',cFile);
            }
        }
        else if(token < ID) fputs(tokenText[i],cFile);
        else fputs(idToText(token), cFile);
    }

    fputs(tokenText[i], cFile);
    fclose(cFile);
}



uint8_t getNextToken(uint32_t * countPtr) /* Increases counter and returns next token */
{
    increaseCounter(countPtr);

    return getToken(*countPtr);

}

uint8_t isUOP(uint32_t countPtr) /* Is token unary operator */
{
    return getToken(countPtr) == NOT;
}

uint8_t isOP(uint32_t countPtr) /* Is token operator */
{
    uint8_t token = getToken(countPtr);

    return  token == ADD || token == SUB || token == MULT ||
            token == DIV || token == EQUALS || token == DIFFERS ||
            token == AND || token == OR || token == GREATER ||
            token == GREATEREQUAL || token == LESS || token == LESSEQUAL;
}

void printError(uint32_t * countPtr, const char * errorMessage) /* Prints error message */
{
    uint8_t token;

    printf("Error in pixel %d.\n%s\n", *countPtr, errorMessage);

    do token = getNextToken(countPtr);
    while(token != ENDLINE || token != ENDLINE );

}

uint8_t isValue(uint32_t * countPtr) /* UNFINISHED */
{
    if(isUOP(*countPtr)) increaseCounter(countPtr);

    while(getToken(*countPtr) != FLOAT)
    {
        switch(getToken(*countPtr))
        {

            case INT:
                increaseCounter(countPtr);
                if(isOP(*countPtr)) increaseCounter(countPtr);
                else if(getToken(*countPtr) == END) return 1;
                else return 0;
                break;
            default:
                return 0;
        }
    }

    while(getToken(*countPtr) == FLOAT || getToken(*countPtr) == INT)
    {
        increaseCounter(countPtr);
        if(isOP(*countPtr)) increaseCounter(countPtr);
        else if(getToken(*countPtr) == END) return 2;
        else return 0;

        if(isUOP(*countPtr)) increaseCounter(countPtr);
    }

    return 0;
}


void analyzeToken(uint32_t * countPtr) /*UNFINISHED*/
{
    uint8_t token = getToken(*countPtr);

    switch(token)
    {
        case IF:

            while(isUOP(*countPtr)) increaseCounter(countPtr);

            if(!isValue(countPtr)) printError(countPtr,"Is not a value.");
            if(getNextToken(countPtr) != END) printError(countPtr,"IF clause doesnt end properly.");

            break;

        case ASSIGN:
            token = getNextToken(countPtr);
            if(token >= ID)
            {
                token -= ID;

            }


    }
}

uint8_t syntaxAnalyzer(FILE * bmp) /* UNFINISHED */
{
    uint8_t token;
    for(uint32_t i = 0; i < tokenCount; i++)
    {
        token = getToken(i);


    }

    return 0;
}

char * getFileName(char * path) /* Returns file name string */
{
    char * start = path, * end, c;

    for(end = path; *end; end++)
    {
        c = *end;
        if(c =='\\' || c == '/')
        {
            start = end + 1;
        }
        else if(c == '.')
        {
            *end = 0;
            return start;
        }
    }

    return "erro";
}


int main(int argc, const char ** argv)
{
    uint32_t numPixels;
    BMPHEADER bmpH;

    if(argc < 2)
    {
        loadPallet();
        printf("Press any key to quit.");
        while(!kbhit());
        return 0;
    }

    const char * filepath = argv[1];

    bmp = fopen(filepath,"rb");

    loadBitmapHeader(bmp, &bmpH);
    numPixels = bmpH.height * bmpH.width;

    goToPixelArray(bmp);
    loadPallet();

    createPixelArray(bmp,bmpH.width,bmpH.height);
    createIdArray();
    createTokenArray(pixelCount);

    printPixel24(pixelArray[0].pix);
    printPixel24(pallet.pixels.initColor.pix);


    lexicalAnalyzer(bmp, numPixels);

    printPixelArray(numPixels);

    //createCCode();
    //syntaxAnalyzer(bmp);
    printf("Compiling Finished!\nPress any key to quit.");

    while(!kbhit());
    fclose(bmp);
    return 0;

}
